Feature/odm user guide v2
genestack/user-docs pull request #10
Opened 2024-06-21 06:26 UTC by genestack-okunitsyn

2024-06-24 19:30 UTC, eeliane requested changes
In general I was pretty confused because it's not clear who is data contributor/consumer/admin in our new texts, because of this it's not easy to understand if information is correct or incorrect based on the all known information about ODM.

Separately, from the text content I'd like to share that it's amazing job! Our user guides haven't ever been so cool, beautiful and user friendly, thanks a lot @MikhailAf! It's great job!🔥🔥

2024-08-02 08:51 UTC, eeliane requested changes

2024-08-02 15:01 UTC, eeliane requested changes

2024-08-02 15:30 UTC, MikhailAf approved these changes

2024-08-02 15:56 UTC, eeliane approved these changes

2024-08-02 15:58 UTC, merged