Add files via upload
genestack/user-docs pull request #33
Opened 2024-09-12 12:40 UTC by srz11d

Updated images from the User Guide, section Admin in UI

2024-09-12 15:36 UTC, srz11d reviewed
Updated images

2024-09-12 19:06 UTC, eeliane requested changes
Hi :) as I see, you've uploaded new images but haven't replaced old images on the page and haven't removed old images, will you do this? otherwise this PR looks like not finished, because only new images have been added to the folder and haven't been used anywhere

2024-09-30 16:40 UTC, eeliane requested changes
Please, check that old unused pictures have been not only replaced but removed from repo;
please, check that list of actions is shown correctly, currently all lists of actions look like 1 sentence;
please, check Table of content on the right side of the user guide on the "Administrator in the User Interface" page, we have lost all links/sections comparing with the develop branch;
please, check comments for changes also.

2024-09-30 16:40 UTC, eeliane commented on docs/user-guide/quick-start/admin-gui.md
> +*The Data Administrator user has the permissions granted to Data Consumer and Data Contributor, as well as Managing Organization permissions to add, edit, and delete Users and Groups in ODM*
Users can't be removed, they only can be deactivated, can we please split here users and groups (groups can be removed)? Also it's not enough to have just Manage organization permission to be able to e.g. remove groups created by some other users, so text anf picture is a bit incorrect

2024-09-30 16:40 UTC, eeliane commented on docs/user-guide/quick-start/admin-gui.md
> +- Click on Profile to access information regarding your user permissions.
Could you please check how 15-19 rows look like in guide? it seems to me that there's some formatting issue because these rows are formatted as a plain long sentence

2024-09-30 16:40 UTC, eeliane commented on docs/user-guide/quick-start/admin-gui.md
> +3. As an **Admin**, you can add, edit, and delete data, users, and groups within the ODM.
on the instance this sentence is started with "1.", not with "3."

2024-09-30 16:40 UTC, eeliane commented on docs/user-guide/quick-start/admin-gui.md
> +3. As an **Admin**, you can add, edit, and delete data, users, and groups within the ODM.
also: users can't be removed, they only can be deactivated; to be able to remove groups created by other users - the user should have permission "Manage groups", it's not enough to have just "Manage organization" permission

2024-09-30 16:40 UTC, eeliane commented on docs/user-guide/quick-start/admin-gui.md
> +As an administrator, you can add, edit, and delete users and groups.
users can't be removed, they only can be deactivated; to be able to remove groups created by other users - the user should have permission "Manage groups", it's not enough to have just "Manage organization" permission

2024-09-30 16:40 UTC, eeliane commented on docs/user-guide/quick-start/admin-gui.md
> +- Click on the three-line menu button at the top left of the dashboard to access the "Groups" section.
Groups can be found on the page on Groups app, not "Users and permissions"

2024-09-30 16:40 UTC, eeliane commented on docs/user-guide/quick-start/admin-gui.md
> +- To change a user's status to active or inactive, click on the three dots on the right side of the user's name.
do we mean the button on the left side?

2024-09-30 16:40 UTC, eeliane commented on docs/user-guide/quick-start/admin-gui.md
> +- A confirmation window will notify you that the password has been successfully changed
shouldn't every separate step be started with the new row?

2024-09-30 16:40 UTC, eeliane commented on docs/user-guide/quick-start/admin-gui.md
> +## Add, update, and delete Groups
Please, add here notification "To add, update, and delete groups **Manage groups** permission is required" as it was previously.

2024-09-30 16:50 UTC, eeliane requested changes

2024-09-30 16:50 UTC, eeliane commented on docs/user-guide/quick-start/admin-gui.md
> +*The Data Administrator user has the permissions granted to Data Consumer and Data Contributor, as well as Managing Organization permissions to add, edit, and delete Users and Groups in ODM*
Also if data administrator is not curator user - he can't edit existing study or import new data

2024-09-30 18:12 UTC, MikhailAf requested changes
Please review syntax, formatting, warnings and notes, and some terms.

2024-09-30 18:12 UTC, MikhailAf commented on docs/user-guide/quick-start/admin-gui.md
> +![Data Model](quick-start-images/1DataModel.png)
Let's call it "User roles" instead of Data Model. ODM Data Model is something [like this ](https://genestack.atlassian.net/wiki/x/BIAt_w)

2024-09-30 18:12 UTC, MikhailAf commented on docs/user-guide/quick-start/admin-gui.md
> +**1. Log into the ODM:**
Please reuse [markdown syntax](https://squidfunk.github.io/mkdocs-material/reference/lists/) to make the list of points actual list, e.g.:
`1. **Log into the ODM**`

2024-09-30 18:12 UTC, MikhailAf commented on docs/user-guide/quick-start/admin-gui.md
> +- Navigate to the ODM homepage.
Please recheck the syntax. The list is not supported now 
<img width="1114" alt="image" src="https://github.com/user-attachments/assets/8c530a00-c8aa-4285-a624-5a361a3e9a39">

2024-09-30 18:12 UTC, MikhailAf commented on docs/user-guide/quick-start/admin-gui.md
> +*Main dashboard of the ODM. Click on your profile to access detailed information about your user capabilities*
There is specific syntax for captions https://squidfunk.github.io/mkdocs-material/reference/images/#image-captions

```
<figure markdown="span">
  ![Image title](https://dummyimage.com/600x400/){ width="300" }
  <figcaption>Image caption</figcaption>
</figure>
```

2024-09-30 18:12 UTC, MikhailAf commented on docs/user-guide/quick-start/admin-gui.md
> +3. As an **Admin**, you can add, edit, and delete data, users, and groups within the ODM.
> on the instance this sentence is started with "1.", not with "3."

The list is not supported due to syntax issues in code. @srz11d I suggest to review the code in IntelliJ on you local machine according to the Training provided by Mikhail Smazhevsky. Additional instructions are here https://genestack.atlassian.net/wiki/x/AoDu7

2024-09-30 18:12 UTC, MikhailAf commented on docs/user-guide/quick-start/admin-gui.md
> +# Use Case Example: Add and update Users
The main header syntax is used twice. That's why the Table of content is broken. Use ## instead.
<img width="228" alt="image" src="https://github.com/user-attachments/assets/dac8e9f2-e6e6-4535-bf2f-6d22cb8f6e8b">
<img width="256" alt="image" src="https://github.com/user-attachments/assets/d29b959b-f156-4cf0-a830-5e182ee9896a">

2024-09-30 18:12 UTC, MikhailAf commented on docs/user-guide/quick-start/admin-gui.md
> +![Users](quick-start-images/4Users.png)
It is also available from Main Dashboard if user have permissions 
<img width="1214" alt="image" src="https://github.com/user-attachments/assets/fcd9fcd6-be60-4b6b-aee7-64ea0c2ef730">

2024-09-30 18:12 UTC, MikhailAf commented on docs/user-guide/quick-start/admin-gui.md
> +*To access User and permissions, click on the three-line menu at the top left of the dashboard. This will display a menu where you can access **Users and permissions***
Captions syntax

And `***` is not supported, space is needed `** *`
<img width="865" alt="image" src="https://github.com/user-attachments/assets/fa1998f0-511d-49d7-aeeb-be5cebedaa4a">

2024-09-30 18:12 UTC, MikhailAf commented on docs/user-guide/quick-start/admin-gui.md
> +**2. Add new users**
List syntax

2024-09-30 18:12 UTC, MikhailAf commented on docs/user-guide/quick-start/admin-gui.md
> +- Click on Add new user.
I suggest to keep `+ New User`

2024-09-30 18:12 UTC, MikhailAf commented on docs/user-guide/quick-start/admin-gui.md
> +- This action will open a new window where you can type the details for the new user: New User 2024
I suggest to avoid particular dates in user guide

2024-09-30 18:12 UTC, MikhailAf commented on docs/user-guide/quick-start/admin-gui.md
> +**3. Confirm New Members**
List syntax

2024-09-30 18:12 UTC, MikhailAf commented on docs/user-guide/quick-start/admin-gui.md
> +- Click on Add new user.
And mark each button **bold** or use other formatting options https://squidfunk.github.io/mkdocs-material/reference/formatting/

2024-09-30 18:12 UTC, MikhailAf commented on docs/user-guide/quick-start/admin-gui.md
> +- After adding the details, click Add to confirm. The new member will be part of the ODM
Mark **Add** button

2024-09-30 18:12 UTC, MikhailAf commented on docs/user-guide/quick-start/admin-gui.md
> +- After adding the details, click Add to confirm. The new member will be part of the ODM
full stop

2024-09-30 18:12 UTC, MikhailAf commented on docs/user-guide/quick-start/admin-gui.md
> +*Confirmation the recently added user, New User 2024, is now part of ODM*
Captions syntax and suggest to avoid dates

2024-09-30 18:12 UTC, MikhailAf commented on docs/user-guide/quick-start/admin-gui.md
> +- Use the search bar to find users you want to grant or revoke permissions to
full stop

2024-09-30 18:12 UTC, MikhailAf commented on docs/user-guide/quick-start/admin-gui.md
> +*Access the **Users and Permissions** section by clicking on the three-line menu at the top left of the dashboard*
full stop

2024-09-30 18:12 UTC, MikhailAf commented on docs/user-guide/quick-start/admin-gui.md
> +- On the main dashboard, click on the three-line menu button at the top left
full stop

2024-09-30 18:12 UTC, MikhailAf commented on docs/user-guide/quick-start/admin-gui.md
> +- This action will open a new window where you can type the details for the new user: New User 2024
full stop

2024-09-30 18:12 UTC, MikhailAf commented on docs/user-guide/quick-start/admin-gui.md
> +- Click on your profile (top right of the main page)
full stop

2024-09-30 18:12 UTC, MikhailAf commented on docs/user-guide/quick-start/admin-gui.md
> +**1. Accessing the Permissions Menu:**
List syntax

2024-09-30 18:12 UTC, MikhailAf commented on docs/user-guide/quick-start/admin-gui.md
> +**2. Change User Password:**
List syntax

2024-09-30 18:12 UTC, MikhailAf commented on docs/user-guide/quick-start/admin-gui.md
> +- Click on the three-line menu button at the top left of the dashboard to access the "Groups" section.
Available from the main Dashboard as well for user with Manage Group permission
<img width="812" alt="image" src="https://github.com/user-attachments/assets/91015a2b-4819-49dc-bdf9-dd4bc75e86e5">

2024-09-30 18:12 UTC, MikhailAf commented on docs/user-guide/quick-start/admin-gui.md
> +***Create a new group**. Access the Groups section. A list of the available groups will be displayed. Click on **+New Group** to create a new group. Select a name for the new group, for example, **De
Syntax 
<img width="840" alt="image" src="https://github.com/user-attachments/assets/92d20741-b1db-4490-b6af-85f02fa45263">

2024-09-30 18:12 UTC, MikhailAf commented on docs/user-guide/quick-start/admin-gui.md
> +- Click on the +New members button to add members to the group.
Mark the button

2024-09-30 18:12 UTC, MikhailAf commented on docs/user-guide/quick-start/admin-gui.md
> +*Add new members to the group by clicking on **+New members**. A new window will appear where you can select users from the list or you can use the search bar to find specific users, e.g., **New User
`** *`

2024-09-30 18:12 UTC, MikhailAf commented on docs/user-guide/quick-start/admin-gui.md
> +**Important Note**: Only members designated as **Group members** can be removed. If the user you intend to remove is an administrator, you must first ensure that another member is assigned as the gro
Admonitions syntax for notes and important information https://squidfunk.github.io/mkdocs-material/reference/admonitions/ Some examples here in User Guide
https://odm.demo.genestack.com/user-docs/user-guide/quick-start/admin-api/#use-case-example-delete-data-in-odm

2024-09-30 18:12 UTC, MikhailAf commented on docs/user-guide/quick-start/admin-gui.md
> -!!! warning "To add, update, and delete groups "Manage groups" permission is required."
We should keep this warning and add it everywhere for Groups OR Add it at the very beginning of Groups subsection

2024-09-30 18:12 UTC, MikhailAf commented on docs/user-guide/quick-start/admin-gui.md
> +Note that **deleting groups is a permanent action**.
Admonitions syntax for notes and important information https://squidfunk.github.io/mkdocs-material/reference/admonitions/ Some examples here in User Guide https://odm.demo.genestack.com/user-docs/user-guide/quick-start/admin-api/#use-case-example-delete-data-in-odm

2024-09-30 18:12 UTC, MikhailAf commented on docs/user-guide/quick-start/admin-gui.md
> +***Delete groups**. Navigate to the group you intend to delete, e.g. **Group Demo version 3**. Click on the three dots on the right side and click on Delete group. A notification will appear to confi
Syntax 
<img width="836" alt="image" src="https://github.com/user-attachments/assets/512952ae-468f-4899-aaed-c0e218cafb25">

2024-09-30 18:12 UTC, MikhailAf commented on docs/user-guide/quick-start/admin-gui.md
> +***Edit group members**. You can change the roles for the members to either **group members** or **group administrators**. Keep in mind that each group requires at least one admin.*
Syntax 
<img width="825" alt="image" src="https://github.com/user-attachments/assets/ade86907-b085-4da4-a382-3c4ffc9ee5e6">

2024-10-07 16:45 UTC, srz11d commented on docs/user-guide/quick-start/admin-gui.md
> +
Can we add the link to the section mentioned above? (User, Roles, Permissions)

2024-10-08 11:04 UTC, srz11d reviewed
The syntax and markdowns have been amended

2025-02-21 21:49 UTC, MikhailAf commented on docs/user-guide/quick-start/admin-gui.md
> +3. As an **Admin**, you can add, edit, and delete data, users, and groups within the ODM.
Checked, everything is updated

2025-02-21 21:52 UTC, MikhailAf commented on docs/user-guide/quick-start/admin-gui.md
> +As an administrator, you can add, edit, and delete users and groups.
Updated, checked.

2025-02-21 22:26 UTC, MikhailAf commented on docs/user-guide/quick-start/admin-gui.md
> +
Added

2025-02-21 22:28 UTC, MikhailAf approved these changes, later dismissed

2025-02-21 22:33 UTC, MikhailAf commented on docs/user-guide/quick-start/admin-gui.md
> +*The Data Administrator user has the permissions granted to Data Consumer and Data Contributor, as well as Managing Organization permissions to add, edit, and delete Users and Groups in ODM*
everything is updated

2025-02-21 22:33 UTC, MikhailAf commented
> Please, check that old unused pictures have been not only replaced but removed from repo; please, check that list of actions is shown correctly, currently all lists of actions look like 1 sentence; please, check Table of content on the right side of the user guide on the "Administrator in the User Interface" page, we have lost all links/sections comparing with the develop branch; please, check comments for changes also.

2025-02-24 09:23 UTC, eeliane submitted a review, later dismissed

2025-02-24 09:23 UTC, eeliane commented on docs/user-guide/quick-start/admin-gui.md
> +![Data Model](quick-start-images/1DataModel.png)
It doesn't look as a data model, it's something separate, can we please rename it somehow?

2025-02-24 09:23 UTC, eeliane commented on docs/user-guide/quick-start/admin-gui.md
> +3. As an **Admin**, you can add, edit, and delete data, users, and groups within the ODM.
there's still information that admin can delete users and groups, can we please rephrase it somehow to take into account important details

2025-02-24 09:23 UTC, eeliane commented on docs/user-guide/quick-start/admin-gui.md
> +As an administrator, you can add, edit, and delete users and groups.
can we please mention here that "Manage group" permission is required to remove groups?

2025-02-24 11:15 UTC, MikhailAf commented on docs/user-guide/quick-start/admin-gui.md
> +![Data Model](quick-start-images/1DataModel.png)
You mean change the image name? 
<img width="884" alt="image" src="https://github.com/user-attachments/assets/c90085ac-b554-42de-a5f3-ca5f7e7b809a" />

2025-02-24 11:17 UTC, MikhailAf commented on docs/user-guide/quick-start/admin-gui.md
> +![Data Model](quick-start-images/1DataModel.png)
done :)

2025-02-24 11:21 UTC, eeliane approved these changes, later dismissed

2025-02-24 11:29 UTC, eeliane approved these changes

2025-02-24 12:57 UTC, merged