Updated Version of Admin in GUI
genestack/user-docs pull request #51
Opened 2024-10-11 15:10 UTC by srz11d

The text has been changed considering previous revisions. In addition, the figures have been updated

2024-10-21 10:34 UTC, eeliane commented
Please, let's finish with the PR https://github.com/genestack/user-docs/pull/33, and only after that create/work with new PRs with changes in the "Admin in GUI" section. I'm a bit confused now because it's not clear what is the difference between this PR and https://github.com/genestack/user-docs/pull/33, and it's pretty difficult and time consuming to review almost the same changes that have been already reviewed and have change requests in separate PR.

2024-10-23 08:26 UTC, eeliane requested changes

2024-10-23 08:26 UTC, eeliane commented on docs/user-guide/quick-start/admin-gui.md
> +To add, update, and delete groups **Manage groups** permission is required.
Can we please somehow add more details here? I'm a bit confused because this permission is needed only to work with groups that have been created by some other user

2024-10-23 08:26 UTC, eeliane commented on docs/user-guide/quick-start/admin-gui.md
> +To add, update, and delete groups **Manage groups** permission is required.
Part of requirements for this permission:

User with this permission can:

- get all user groups and its members on the instance via API and in GUI in the “Groups” application;
- create a user group;
- delete a user groups, even if the user is not an admin of the group;
- add to and remove from a group its members, even if the user is not an admin of the group.

User without this permission - **the rights of users without this permission remain unchanged and they can work with only groups in which they have membership**.

So, user without this permission also can create group and edit it or delete, because he's the owner.

2024-10-23 08:26 UTC, eeliane commented on docs/user-guide/quick-start/admin-gui.md
> +        In order to be able to create, edit and delete groups, the user should have the **Manage organization** permission.
same here, can we please somehow mention that not in all cases the user should have this permission? or at least mention that we are talking about managing any group that even have been created by some other user?

2025-01-21 19:18 UTC, eeliane requested changes
Looks perfect, good job, I've left just 1 comment 🔥

2025-01-21 19:18 UTC, eeliane commented on docs/user-guide/quick-start/admin-gui.md
> +    Only members designated as **Group members** can be removed. If the user you intend to remove is an administrator, you must first ensure that another member is assigned as the group administrator
Probably these sentences describe the same case, let's remove one of them? 
>If the user you intend to remove is an administrator, you must first ensure that another member is assigned as the group administrator, as each group must have at least one administrator. 
>If you want to remove a user with the role of admin, you need to assign another administrator within the group.

2025-02-24 18:37 UTC, MikhailAf approved these changes

2025-02-28 09:36 UTC, MikhailAf commented on docs/user-guide/quick-start/admin-gui.md
> +    Only members designated as **Group members** can be removed. If the user you intend to remove is an administrator, you must first ensure that another member is assigned as the group administrator
Changes were provided

2025-02-28 09:40 UTC, eeliane approved these changes

2025-02-28 09:47 UTC, merged