Updated section Create New Study
genestack/user-docs pull request #59
Opened 2024-10-21 11:56 UTC by srz11d

The whole section Create New Study has been updated, including new sections and screenshots

2024-10-22 19:07 UTC, eeliane requested changes
Good job! I've added just comment one place that should be fixed. Also, please, remove all replaced images that are not used anywhere anymore. We need to keep in this repo only images that we use.

2024-10-22 19:07 UTC, eeliane commented on docs/user-guide/doc-odm-user-guide/create-study.md
> +    1. **Understanding Templates**: For more information about what a template is and how it works, refer to the [Key Concepts section](https://odm.demo.genestack.com/user-docs/user-guide/key-concept
Probably we'd like to use the link related to the template section, but please, do not provide links to the odm.demo instance (external links), you can and have to provide internal link

2025-01-24 16:30 UTC, eeliane requested changes
Looks good, I have just one minor comment

2025-01-24 16:30 UTC, eeliane commented on docs/user-guide/doc-odm-user-guide/create-study.md
> +1. Click on **Create new study**: Start by selecting the option to create a New Study on the main dashboard (a) or from the menu in the top left corner, then click on “Create a New Study” (b).
>then click on “Create a New Study”

the button on the screenshot is called "Create new study"

2025-03-14 10:48 UTC, MikhailAf commented on docs/user-guide/doc-odm-user-guide/create-study.md
> +    1. **Understanding Templates**: For more information about what a template is and how it works, refer to the [Key Concepts section](https://odm.demo.genestack.com/user-docs/user-guide/key-concept
Done

2025-03-14 10:48 UTC, MikhailAf commented on docs/user-guide/doc-odm-user-guide/create-study.md
> +1. Click on **Create new study**: Start by selecting the option to create a New Study on the main dashboard (a) or from the menu in the top left corner, then click on “Create a New Study” (b).
Done

2025-03-14 11:17 UTC, eeliane requested changes

2025-03-14 11:17 UTC, eeliane commented on docs/user-guide/doc-odm-user-guide/create-study.md
> +the menu in the top left corner, then click on “Create a New Study” (b).
Create a New Study -> Create New Study

2025-03-14 11:17 UTC, eeliane commented on docs/user-guide/doc-odm-user-guide/create-study.md
> +    the [Key Concepts section](../key-concepts/key-concepts.md/#templates)). This section provides definitions and details about templates, including how to
please, remove ")" in the end of the sentence

2025-03-14 11:19 UTC, MikhailAf commented on docs/user-guide/doc-odm-user-guide/create-study.md
> +    the [Key Concepts section](../key-concepts/key-concepts.md/#templates)). This section provides definitions and details about templates, including how to
:))))

2025-03-14 11:25 UTC, MikhailAf commented on docs/user-guide/doc-odm-user-guide/create-study.md
> +the menu in the top left corner, then click on “Create a New Study” (b).
Done

2025-03-14 11:25 UTC, MikhailAf commented on docs/user-guide/doc-odm-user-guide/create-study.md
> +    the [Key Concepts section](../key-concepts/key-concepts.md/#templates)). This section provides definitions and details about templates, including how to
Done

2025-03-14 11:35 UTC, eeliane approved these changes

2025-03-14 12:33 UTC, merged