The section Exporting Data has been updated
genestack/user-docs pull request #61
Opened 2024-10-22 12:54 UTC by srz11d

The section has been updated and new screenshots have been added

2024-10-24 10:52 UTC, eeliane requested changes
Great job :) in general everything is okay, could you please check my comment regarding changes that have been added recently in ODM?

2024-10-24 10:52 UTC, eeliane commented on docs/user-guide/doc-odm-user-guide/exporting-data.md
> +* The **Export** button can be accessed from the right side of the dashboard or by clicking on the study title, which will reveal a dropdown menu with the option to export data.
We've added yet another one export button, so your screenshot is outdated comparing with the current develop branch (=1.59 release), could you please check fresh develop branch and update instruction and screenshot?

2025-01-28 13:58 UTC, eeliane requested changes

2025-01-28 13:58 UTC, eeliane commented on docs/user-guide/doc-odm-user-guide/exporting-data.md
> +![3Contents.png](doc-odm-user-guide/images/3Contents.png)
Let's please update this screenshot since after adding data classes to attachments this file has been also updated

2025-01-28 13:58 UTC, eeliane commented on docs/user-guide/doc-odm-user-guide/exporting-data.md
> +* You can export a specific dataset of interest. To do this, navigate to the tab containing the desired analysis and click the **Download file** button.
>navigate to the tab containing the desired analysis

it works only on Data tab, let's please mention this, user can't export e.g. only samples metadata or study metadata

2025-01-28 18:43 UTC, eeliane requested changes

2025-01-28 18:43 UTC, eeliane commented on docs/user-guide/doc-odm-user-guide/exporting-data.md
> -![image](doc-odm-user-guide/images/export-data-menu.png)
please, remove the file export-data-menu.png if we don't use it anymore

2025-01-28 18:43 UTC, eeliane commented on docs/user-guide/doc-odm-user-guide/exporting-data.md
> -![image](doc-odm-user-guide/images/export_button.png)
please, remove the file export_button.png if we don't use it anymore

2025-01-28 18:43 UTC, eeliane commented on docs/user-guide/doc-odm-user-guide/exporting-data.md
> -![image](doc-odm-user-guide/images/export-data-link.png)
please, remove the file export-data-link.png if we don't use it anymore

2025-01-28 18:43 UTC, eeliane commented on docs/user-guide/doc-odm-user-guide/exporting-data.md
> -![image](doc-odm-user-guide/images/add_data-button.png)
please, remove the file add_data-button.png if we don't use it anymore

2025-04-14 12:38 UTC, eeliane requested changes
Please, resolve all conflicts before sending this PR to new review 🤞

2025-04-16 18:58 UTC, eeliane requested changes
Could you please check added from the develop branch gifs? Look like the first gif should be updated, and something should be done with picture and gif at the end of the page :)

2025-05-20 13:51 UTC, MikhailAf approved these changes

2025-05-20 14:56 UTC, MikhailAf requested changes
I am going to review and introduce changes to this article before merging it.

2025-05-21 09:35 UTC, MikhailAf commented
> Could you please check added from the develop branch gifs? Look like the first gif should be updated, and something should be done with picture and gif at the end of the page :)

Was fixed

2025-05-21 11:01 UTC, eeliane approved these changes

2025-05-21 13:51 UTC, MikhailAf approved these changes

2025-05-21 13:52 UTC, merged